import React from 'react';
import { useFields } from '../context/FieldContext';
import { Bug, Cpu, CheckCircle2, AlertTriangle, ShieldCheck, Info } from 'lucide-react';

export default function DiseaseAnalysisPage() {
  const { activeHotspots, selectedField } = useFields();

  const diseaseRegistry = [
    {
      crop: 'Tomato',
      diseaseName: 'Early Blight (Alternaria solani)',
      status: 'SUSPECTED',
      confidence: 0.84,
      severity: 'HIGH',
      visualEvidence: [
        'Concentric dark brown foliage lesions',
        'Chlorosis around leaf margins under RGB band',
        'Localized lower canopy necrosis',
      ],
      pestIndicator: 'None detected',
      recommendedVerification: 'Physically inspect lower canopy foliage for target-shaped lesions; lab testing required before chemical treatment.',
    },
    {
      crop: 'Tomato',
      diseaseName: 'Late Blight (Phytophthora infestans)',
      status: 'SUSPECTED',
      confidence: 0.62,
      severity: 'CRITICAL',
      visualEvidence: [
        'Water-soaked dark leaf blotches',
        'White fungal growth under high relative humidity (>78%)',
      ],
      pestIndicator: 'Minor thrip activity suspected',
      recommendedVerification: 'Check field section drainage and collect leaf tissue samples for laboratory assay.',
    },
    {
      crop: 'Tomato',
      diseaseName: 'Nitrogen Deficiency',
      status: 'INCONCLUSIVE',
      confidence: 0.41,
      severity: 'MEDIUM',
      visualEvidence: [
        'Generalized yellowing of older leaves',
        'Stunted stem elongation index',
      ],
      pestIndicator: 'None',
      recommendedVerification: 'Conduct soil EC and nitrate test in block A.',
    },
  ];

  return (
    <div className="space-y-6 pb-12">
      {/* Page Header */}
      <div className="glass-panel p-6 rounded-3xl border border-slate-800 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-slate-100 flex items-center gap-2">
            🦠 AI Visual Disease & Pest Identification
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Targeted visual diagnostics generated by Ollama Qwen3-VL vision model on extracted hotspot image patches.
          </p>
        </div>

        <div className="px-3.5 py-2 rounded-2xl bg-indigo-950/60 border border-indigo-800 text-indigo-300 text-xs font-mono font-bold flex items-center gap-2">
          <Cpu className="w-4 h-4 text-indigo-400" /> Model: Qwen3-VL (8.8B Vision)
        </div>
      </div>

      {/* Distinction Disclaimer Banner */}
      <div className="p-4 rounded-2xl bg-amber-950/20 border border-amber-800/40 flex items-start gap-3 text-xs text-amber-200">
        <Info className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="font-bold">Agronomic AI Diagnostics Disclaimer</p>
          <p className="text-slate-300 leading-relaxed">
            The AI engine categorizes issues strictly as <strong className="text-amber-300">SUSPECTED</strong>, <strong className="text-slate-400">INCONCLUSIVE</strong>, or <strong className="text-emerald-400">NO_VISIBLE_ABNORMALITY</strong>. Visual AI predictions represent preliminary hypotheses and must not be treated as confirmed without physical laboratory assay or field tissue testing.
          </p>
        </div>
      </div>

      {/* Disease Registry Grid */}
      <div className="space-y-4">
        {diseaseRegistry.map((item, idx) => (
          <div key={idx} className="glass-panel p-6 rounded-3xl border border-slate-800 space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-3">
              <div>
                <div className="flex items-center gap-2">
                  <span className="font-extrabold text-base text-slate-100">
                    {item.diseaseName}
                  </span>
                  <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold font-mono ${
                    item.status === 'SUSPECTED'
                      ? 'bg-amber-950 text-amber-300 border border-amber-800'
                      : item.status === 'NO_VISIBLE_ABNORMALITY'
                      ? 'bg-emerald-950 text-emerald-300 border border-emerald-800'
                      : 'bg-slate-800 text-slate-400 border border-slate-700'
                  }`}>
                    {item.status}
                  </span>
                </div>
                <span className="text-xs text-slate-400">Crop: {item.crop}</span>
              </div>

              <div className="text-right">
                <span className="text-xs text-slate-400 block font-medium">AI Confidence</span>
                <span className="text-xl font-extrabold text-emerald-400 font-mono">
                  {(item.confidence * 100).toFixed(0)}%
                </span>
              </div>
            </div>

            {/* Visual Evidence Checklist */}
            <div className="space-y-2">
              <span className="text-xs font-semibold text-slate-300 block">
                ✓ Visual Evidence Checklist (Qwen3-VL Analysis)
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
                {item.visualEvidence.map((ev, i) => (
                  <div key={i} className="p-3 rounded-xl bg-slate-900 border border-slate-800 text-slate-300 flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                    <span>{ev}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Verification Advice */}
            <div className="p-3.5 rounded-xl bg-slate-900/60 border border-slate-800 text-xs space-y-1">
              <span className="font-semibold text-emerald-400 block">Recommended Verification Step:</span>
              <p className="text-slate-300">{item.recommendedVerification}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
